/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.birthday;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDate;
import java.util.TreeSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author suhru
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    LocalDate a=LocalDate.now();
    boolean firsttime=true;
    static String filepath="C:\\Users\\suhru\\OneDrive\\Desktop\\birthday.csv";
    public NewJFrame() {
        initComponents();
                Thread t;
        t = new Thread(new Runnable(){
            @Override
            public void run(){
                try {
                    
                    while(true){
                        setter();
                        Thread.sleep(1000);
                    }
                } catch (IOException | InterruptedException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t.start();
    }
    private void setter() throws FileNotFoundException, IOException{
        if(a.equals(LocalDate.now()) && !firsttime){
            return ;
        }
        firsttime=false;
        this.a=LocalDate.now();
        //System.out.print("1");
        int Current_month=a.getMonthValue();
        int Current_year=a.getYear();
        int Current_date=a.getDayOfMonth();
        birthday current=new birthday(null,Current_year+"/"+Current_month+"/"+Current_date);
        FileReader f=new FileReader(filepath);
        BufferedReader fr;
        fr = new BufferedReader(f);
        String data=fr.readLine();
        TreeSet <birthday>ts=new <birthday>TreeSet();
        while(data!=null){
            String datatemp[]=data.split(",");
            ts.add(new birthday(datatemp[0],datatemp[1]));
            data=fr.readLine();
        }
       //System.out.println(ts);
       int i;
       Object arr[]= ts.toArray();
       for(i=0;i<arr.length;i++){
           if(current.compare(current,(birthday)arr[i])==0){
               JLabel label = new JLabel("Wish "+((birthday)arr[i]).name+" Happy Birthday on their "+String.valueOf(Current_year-((birthday)arr[(i)%arr.length]).yy)+" th Birthday");
                label.setFont(new Font("Arial", Font.BOLD, 18));
               JOptionPane.showMessageDialog(this,label,"Wish "+((birthday)arr[i]).name+" Happy birthday", JOptionPane.INFORMATION_MESSAGE,new ImageIcon("C:\\Users\\suhru\\OneDrive\\Desktop\\download.jfif"));
           }
           if(current.compare(current,(birthday)arr[i])>0){
               break;
           }
       }
       this.bday1_date.setText(((birthday)arr[(i)%arr.length]).date()+"   "+String.valueOf(Current_year-((birthday)arr[(i)%arr.length]).yy+" Years old"));
       this.bday2_date.setText(((birthday)arr[(i+1)%arr.length]).date()+"   "+String.valueOf(Current_year-((birthday)arr[(i+1)%arr.length]).yy+" Years old"));
       this.bday3_date.setText(((birthday)arr[(i+2)%arr.length]).date()+"   "+String.valueOf(Current_year-((birthday)arr[(i+2)%arr.length]).yy+" Years old"));
       this.bday1_name.setText(((birthday)arr[i%arr.length]).name);
       this.bday2_name.setText(((birthday)arr[(i+1)%arr.length]).name);
       this.bday3_name.setText(((birthday)arr[(i+2)%arr.length]).name);
       fr.close();
       arr=null;
       ts=null;
       System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        add = new javax.swing.JButton();
        changedata = new javax.swing.JButton();
        viewdata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bday1_name = new javax.swing.JLabel();
        bday2_name = new javax.swing.JLabel();
        bday1_date = new javax.swing.JLabel();
        bday2_date = new javax.swing.JLabel();
        bday3_date = new javax.swing.JLabel();
        bday3_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Birthday Reminder");
        setBackground(new java.awt.Color(51, 0, 255));

        add.setText("Add birthday");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        changedata.setText("Change Data File(Currently not available)");

        viewdata.setText("View Data File");
        viewdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Upcoming Birthdays ");

        bday1_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bday1_name.setText("jLabel2");

        bday2_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bday2_name.setText("jLabel2");

        bday1_date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bday1_date.setText("jLabel2");

        bday2_date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bday2_date.setText("jLabel2");

        bday3_date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bday3_date.setText("jLabel2");

        bday3_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bday3_name.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Birthday Reminder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changedata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addComponent(bday1_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bday1_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bday2_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bday2_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bday3_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bday3_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bday1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bday1_date, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bday2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bday2_date, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bday3_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bday3_date, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changedata, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewdata, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        add a=new add();
        a.jTextField1.setText("dd/mm/yyyy");
        a.setVisible(true);
       
    }//GEN-LAST:event_addActionPerformed

    private void viewdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdataActionPerformed
        try {
            // TODO add your handling code here:
            File a=new File(filepath);
            Desktop ab= Desktop.getDesktop();
            ab.open(a);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewdataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame a=new NewJFrame();
                a.setVisible(true);
            }
        });
    }
    protected void finalize() throws Throwable{
        super.finalize();
        System.out.println("Finalized");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel bday1_date;
    private javax.swing.JLabel bday1_name;
    private javax.swing.JLabel bday2_date;
    private javax.swing.JLabel bday2_name;
    private javax.swing.JLabel bday3_date;
    private javax.swing.JLabel bday3_name;
    private javax.swing.JButton changedata;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton viewdata;
    // End of variables declaration//GEN-END:variables
}
